### ISSUE TITLE
How to show different price for different warehouse on same product?

### ISSUE THREAD

**Issue by IHEnan99** [fahadmahmood8/stock-locations-for-woocommerce#110]
Hi hope you are doing well. I like your plugins idea and I think your plugin can also fulfil my requirements. Can you let me know if your plugin offers the functionality to set different price for same product for different warehouse?

**Comment by oppssssss** [comment]
Thumbs Up!

**Comment by fahadmahmood8** [comment]
Thank you for this suggestion, it will help to manage a different price including shipping and taxes (FEE) according to the stock location selected. I am not implementing it immediately but adding this option in upcoming version 1.6.8. Values will be saved but will have no effect for now. Let me study the plugin files in depth to handle the ripple effects.
