### ISSUE TITLE
Default location stock

### ISSUE THREAD

**Issue by ysaellisa** [fahadmahmood8/stock-locations-for-woocommerce#111]
Hello 
We have two location stocks for our products, we need one to be always used by default and the other one to be used if the first one is empty, I can't find the way to do that, could you please help me to resolve that ?
Thanks by advance,
Ysabel

**Comment by fahadmahmood8** [comment]
Dear Ysabel,

Have you check the priority input box option on stock location? Priority number decides if stock is not sufficient so allocate from the next stock location.

Thanks,
Fahad
