### ISSUE TITLE
Plug-in causes out of stock message on products with variations

### ISSUE THREAD

**Issue by jeroendk** [fahadmahmood8/stock-locations-for-woocommerce#125]
All our variation products show out of stock after selecting a variation, while all variations are on stock and have sufficient stock quantity.
After disabling the plugin the variations show as in stock. 

Products can still be bought but only show a stock message.

**Comment by fahadmahmood8** [comment]
@jeroendk I need a user who can go through all the settings and related pages where stock qty. and prices can have effect. Till yet, I am mostly receiving the bug reports but every user comes up with a different scenario. If you are comfortable joining me in testing, kindly use the urgent help option under the help tab on settings page.
