### ISSUE TITLE
WP ALL Import "You need to add a stock location to this product."

### ISSUE THREAD

**Issue by tomkolp** [fahadmahmood8/stock-locations-for-woocommerce#126]
Imports new products to the store, after import, additional warehouses are not turned on.
![image](https://user-images.githubusercontent.com/39633242/169785464-c5d1d622-11d2-445d-a185-d380c20d1853.png)
How to automatically include these warehouses on import?
WP ALL Import mapping:
![image](https://user-images.githubusercontent.com/39633242/169786301-a817b263-f635-465d-9063-b218713896b8.png)
WP ALL Import settings import:
![image](https://user-images.githubusercontent.com/39633242/169786430-cb0b14f0-2830-40d7-818d-ceb61c509b51.png)

When you manually enable these stores after importing, the stock update works. Only on the first import, additional warehouses are not active.

**Comment by fahadmahmood8** [comment]
I did not check this case yet, kindly reach me through the help tab on settings page using urgent help so I can have some insights regarding wp all import settings. I will take care of this case as well.

**Comment by tomkolp** [comment]
Unfortunately, all remote desktop connections and screen sharing are blocked on my network. If possible, I can provide information about all the settings I use.

**Comment by fahadmahmood8** [comment]
Then record a video so I can repeat the steps to produce the same issue on my end, I am a developer but not a good user as you are.

**Comment by karamans** [comment]
Hello. The problem still persists and it is very easy to reproduce it: it is enough to import any product through wp all import. Warehouses are not automatically turned on. You have to turn them on manually

**Comment by fahadmahmood8** [comment]
No need to do it manually, when we import through WooCommerce way, locations are turned ON automatically if the stock value is positive. Please try running the cron job after importing through wp all import, hopefully it will fix the issue, else I will add a command for it in the next version.
