### ISSUE TITLE
Currency symbol in the price field

### ISSUE THREAD

**Issue by tomkolp** [fahadmahmood8/stock-locations-for-woocommerce#127]
After activating the "Stock Locations for Woocommerce" plugin, the currency symbol appears in the price field, this causes a problem in the "wp desk omnibus" plugin.
![image](https://user-images.githubusercontent.com/39633242/170986339-532943af-334d-4b5f-9bf6-7c67d7067f80.png)

**Comment by fahadmahmood8** [comment]
Version 1.9.8 should resolve this issue, kindly check and confirm.
