### ISSUE TITLE
Unable to select variable product quantity on front end

### ISSUE THREAD

**Issue by bnbrndn** [fahadmahmood8/stock-locations-for-woocommerce#128]
I have a variable product which has stock in all locations and is enabled in all loctions. When trying to select the variation on the front end I am getting a console error of:

Uncaught TypeError: Cannot read properties of undefined (reading '0')

**Comment by fahadmahmood8** [comment]
@bnbrndn I couldn't reproduce this issue because I am working on a new version. So please wait if upcoming version gives you the same error, paste your URL here so I can check the details.
