### ISSUE TITLE
"in stock" cannot be translated

### ISSUE THREAD

**Issue by tomkolp** [fahadmahmood8/stock-locations-for-woocommerce#129]
Could not translate "in stock" in newly added function.  In the "old" places the translations work.
![image](https://user-images.githubusercontent.com/39633242/174438451-d6068bc4-a62c-46a0-9195-71f8a2749e76.png)

**Comment by fahadmahmood8** [comment]
I will give another round to the translation as newly developed modules are translatable but not yet translated.
