### ISSUE TITLE
Can't add more than one product

### ISSUE THREAD

**Issue by pappu-corridor** [fahadmahmood8/stock-locations-for-woocommerce#132]
https://ct-host.net/delicious88/location/9055-marbach-rd-san-antonio-tx-usa/

Can not add more than one product in location page, but added on single product page. Can you please help me out.

**Comment by fahadmahmood8** [comment]
@pappu-corridor I can surely help you out, actually if there is any problem in the code so you are helping me to sort it out. Kindly confirm on this page you are already displaying the products category-wise, am I right?
