### ISSUE TITLE
When create order from woocommerce rest api, the quantity of the items not decrease

### ISSUE THREAD

**Issue by fabio-alkimia** [fahadmahmood8/stock-locations-for-woocommerce#137]
Hello!!!
I have 3 locations (A, B, C) set up in woocommerce with this plugin.
I created an order using Woocommerce's REST API (https://woocommerce.github.io/woocommerce-rest-api-docs/?php#create-an-order).

When I send the request, the order is correctly sent to woocommerce and I see it in the list.. All ok.
But the problem is: How do I specify which location I cover the product from? And why the quantity of the product not decreased at the time of purchase (order status "completed")?

Thank you!

Here's some screenshots.

Quantity before:
<img width="137" alt="Schermata 2022-11-11 alle 12 53 18" src="https://user-images.githubusercontent.com/102519891/201335125-7a8f2daf-42c8-4464-9ab4-428b52f5de51.png">

The body of the request:
<img width="367" alt="Schermata 2022-11-11 alle 12 47 04" src="https://user-images.githubusercontent.com/102519891/201334186-4d47d6b3-11d3-4758-8ea7-1dc81cb6f977.png">

The order in orders list
<img width="1735" alt="Schermata 2022-11-11 alle 12 49 12" src="https://user-images.githubusercontent.com/102519891/201334599-7449327f-897f-44be-8067-a214dae7914a.png">

The products in the order, with quantity buying but without location (the problem)
<img width="1441" alt="Schermata 2022-11-11 alle 12 50 27" src="https://user-images.githubusercontent.com/102519891/201334829-8db85b1b-f47e-4cbd-9a48-c491ad009eb6.png">

Quantity after:
<img width="137" alt="Schermata 2022-11-11 alle 12 53 18" src="https://user-images.githubusercontent.com/102519891/201335161-5bbbd8e6-5e8c-43b8-b4d3-5e8e79da26da.png">

In this case the quantity (location quantity and "total" quantity not decrease)

**Comment by fahadmahmood8** [comment]
If products are enabled with manage stock then the following action hook is working for stock reduction 

`add_action( 'woocommerce_reduce_order_stock', array( $this, 'reduce_order_items_locations_stock' ), 10, 1 );`

And if manage stock is not enabled then the following action hooks are working

`				add_action( 'woocommerce_payment_complete', array( $this, 'reduce_order_items_locations_stock' ), 10, 1 );
				add_action( 'woocommerce_order_status_completed', array( $this, 'reduce_order_items_locations_stock' ), 10, 1 );
				add_action( 'woocommerce_order_status_processing', array( $this, 'reduce_order_items_locations_stock' ), 10, 1 );
				add_action( 'woocommerce_order_status_on-hold', array( $this, 'reduce_order_items_locations_stock' ), 10, 1 );`
