### ISSUE TITLE
Location priority for multiple stock locations

### ISSUE THREAD

**Issue by nikhilv360** [fahadmahmood8/stock-locations-for-woocommerce#139]
Hi,

We are testing the plugin for having orders shipped from multiple stock locations.

The Example in our case:-
We have three locations with priority 10, 20 and 30.

According to your plugin logic, the higher-priority location should be selected first. Still, it is not happening in our case as the location with priority 10 is always getting selected first for stock reduction and then the following location selected is 30.

Screenshot links for example:
Stock locations – https://prnt.sc/n86kBXUAXBL1
Order info – https://prnt.sc/cPY9Ma0__jYt

This is not following the priority order 30 > 20 > 10 and we are having issues with the order meta.

Can you please help us with this issue?

Let me know if you any more details from my end.

Thanks.

**Comment by fahadmahmood8** [comment]
I have already pinned the support thread you created regarding the location priority number, closing this issue here but the other support thread will be continued with you further.
