### ISSUE TITLE
eBay sync in different eBay’s from specific location

### ISSUE THREAD

**Issue by TCP1952** [fahadmahmood8/stock-locations-for-woocommerce#140]
Hello, I am Klaus from TOP CLASSIC PARTS LLC in aft. Myers FL.
We started just we a 2nd production and fulfillment location in Germany. They have their own stock levels, 
We use eBay and sync our orders etc. with wp-lister to eBay.com from Ft. Myers, and want to sync from location Germany to other European eBay’s too, 
Do you work together with those guys? Do you think your plug-in will help us to get our idea realized? Thx Klaus

**Comment by fahadmahmood8** [comment]
We do not work together with those guys yet but possibly in future we will be working. For now we can use the API end points to sync between the two platforms.
