### ISSUE TITLE
Greyed out Stock Quantity

### ISSUE THREAD

**Issue by beeg716** [fahadmahmood8/stock-locations-for-woocommerce#143]
When editing a product, all of the Stock quantity inputs are greyed out. See screenshot. 

<img width="1555" alt="Screenshot 2023-04-04 095949" src="https://user-images.githubusercontent.com/129886461/229864179-9e55fb77-2050-4bba-a601-438322b964fa.png">

I disabled the Stock Locations plugin and then I can enter stock quantities. So the plugin is causing the issue.

<img width="1549" alt="Screenshot 2023-04-04 100241" src="https://user-images.githubusercontent.com/129886461/229864808-7717cd98-6c68-494d-9eec-6697eb4ff1e1.png">

I also tried to uncheck locations for the product, save and then I can enter stock quantities. This can't be a fix since I need to be able to update the total stock when locations are selected but just something I noticed.

Can you please provide any assistance?

**Comment by arwinvdv** [comment]
If you want to change the stock quantity of a variable product, go in the edit product page to the tab Stock Locations (above Attributes).

**Comment by beeg716** [comment]
Thanks! However, how can I edit the total stock?

**Comment by arwinvdv** [comment]
How did you think this would work? When you adjust the total, how does the plugin know at which location to increase or decrease something?

**Comment by beeg716** [comment]
It should work by allowing to enter the total and then in the Stock Locations, you'd enter the individual location stock quantities and see the total you just entered. Why does this number show if you cant edit the total when the locations are enabled? Just a question. If that's the way it supposed to work, then that's fine 👍
<img width="704" alt="image" src="https://user-images.githubusercontent.com/129886461/230134848-38e340d0-2999-453e-8d4b-a126109d6269.png">

**Comment by fahadmahmood8** [comment]
Sorry for being late here, thank you @arwinvdv for explaining the stock qth. field under stock locations. Total stock value get updated usually on product update and also through the Cron jobs rounds. So don't worry about this wrong total number, as soon as your cron job will start working, these kind of small updates will be handled easily.
