### ISSUE TITLE
Stock location inventory not being saved

### ISSUE THREAD

**Issue by SmahtIdeas** [fahadmahmood8/stock-locations-for-woocommerce#146]
Trying to see if this will be a working solution for my client. When I set the inventory for a simple product, then go to Stock locations and set that inventory, nothing is being saved after update.
What I am looking to accomplish is a plugin that will work with Sheet Editor and combine inventories from two locations.
If possible, would hire you to do this project.
Reply to jonathan@smahtideas.com
Thanks!

**Comment by SmahtIdeas** [comment]
A little more detail.
1) Client has two inventory locations.
2) Inventory is updated in Google Sheets, 1 column for Floor Stock, 1 column for Back Stock, 1 column that totals both for total Stock.
3) WooComerce website uses WP Sheet Editor - WooCommerce Products to bulk edit all products and variations
4) Approximately 1800 products - simple and variations
5) Need to figure out how to show the same columns in Sheet Editor that are in Google Sheets.
6) Will be using [Google Sheets Sync](https://wpsheeteditor.com/extensions/google-sheets/) to keep both updated.
Hopefully you are able to help.
Thanks!
Jonathan

**Comment by fahadmahmood8** [comment]
> Trying to see if this will be a working solution for my client. When I set the inventory for a simple product, then go to Stock locations and set that inventory, nothing is being saved after update. What I am looking to accomplish is a plugin that will work with Sheet Editor and combine inventories from two locations. If possible, would hire you to do this project. Reply to [jonathan@smahtideas.com](mailto:jonathan@smahtideas.com) Thanks!

Please check if you enabled the stock locations? There is a toggle button to enable/disable locations on edit page.

**Comment by fahadmahmood8** [comment]
> A little more detail.
> 
>     1. Client has two inventory locations.
> 
>     2. Inventory is updated in Google Sheets, 1 column for Floor Stock, 1 column for Back Stock, 1 column that totals both for total Stock.
> 
>     3. WooComerce website uses WP Sheet Editor - WooCommerce Products to bulk edit all products and variations
> 
>     4. Approximately 1800 products - simple and variations
> 
>     5. Need to figure out how to show the same columns in Sheet Editor that are in Google Sheets.
> 
>     6. Will be using [Google Sheets Sync](https://wpsheeteditor.com/extensions/google-sheets/) to keep both updated.
>        Hopefully you are able to help.
>        Thanks!
>        Jonathan

Please read the following support thread to understand that how you can set cron job when you have 1800+ products.
https://wordpress.org/support/topic/stock-not-reducing-when-orders-received/#post-17016960
