### ISSUE TITLE
When the order status is changed, the quantity of items is returned. 

### ISSUE THREAD

**Issue by AlexanderGitSafronov** [fahadmahmood8/stock-locations-for-woocommerce#147]
When the order status is changed, the quantity of items is returned.  As soon as I change the order status to "pending payment" to edit the order, the quantity of goods is returned. And whatever I change it does not affect the quantity of this product or any other.

**Comment by fahadmahmood8** [comment]
I understand but it is just a use-case you brought to my attention, please suggest some improvement in the code as you look code savvy.
