### ISSUE TITLE
Checkout page broken

### ISSUE THREAD

**Issue by ThatsCold** [fahadmahmood8/stock-locations-for-woocommerce#150]
Hi!
I have problem to do a checkout with this plugin activated, it throws me an error. If I deactivate the plugin it works fine to do a payment.

felix

**Comment by fahadmahmood8** [comment]
Dear Felix,

I am available to help you, can you please check your error log so I can fix the error behind. Let me know if you can join me on Slack or on any other platform so we can meet?
