### ISSUE TITLE
Allow to modify stock allocation email subject

### ISSUE THREAD

**Issue by chingologram** [fahadmahmood8/stock-locations-for-woocommerce#151]
The subject for the notification email is hardcoded in src/helpers/helper-slw-mail.php, line 41:
`$subject = __('Stock allocated in', 'stock-locations-for-woocommerce') . ' ' . $term->name; `

Could we add a filter as follows in line 42 ?

`apply_filters('slw_stock_allocation_notification_subject', $subject, $term, $quantity, $item);`

The reason for this is that we want to group notifications for the same order under the same email thread for readability purposes.

Cheers!

**Comment by fahadmahmood8** [comment]
I have added this filter line in the plugin, you will get it in the next version, thank you.
