### ISSUE TITLE
Inconsistent calls to slw_stock_allocation_notification_message

### ISSUE THREAD

**Issue by chingologram** [fahadmahmood8/stock-locations-for-woocommerce#153]
In the mail helper, the filter for email message overriding is called twice, with different parameter types. 
See below:

https://github.com/fahadmahmood8/stock-locations-for-woocommerce/blob/7322f33ac3b7193b0261d9cc629160c1c99c2aaa/src/src/helpers/helper-slw-mail.php#L46

I added a PR https://github.com/fahadmahmood8/stock-locations-for-woocommerce/pull/152 with a fix for this. Feel free to review and merge.

**Comment by fahadmahmood8** [comment]
Thank you, already added/merged.
