### ISSUE TITLE
There is a problem with the locations plugin, please help me

### ISSUE THREAD

**Issue by Sov888** [fahadmahmood8/stock-locations-for-woocommerce#156]
Hello! I wrote a small script and am trying to add quantities for different locations via the API! But there's a problem
1 The number in the database changes, but on the website and in the admin panel it does not change.
2 How to add quantity to those products that do not have locations assigned to them in the admin panel manually I won’t be able to have too many of them
3 I don’t understand from the variations whether the remainder is added correctly or not!
I would be grateful for your help! I'm attaching the script! 
[stock_updater.php.zip](https://github.com/user-attachments/files/16615166/stock_updater.php.zip)

**Comment by fahadmahmood8** [comment]
Actually you are not considering the cron job run, if you will run the cron job scripts available under a tab on the plugin settings page, you will get it work.
