### ISSUE TITLE
Incompatible with HPOS feature

### ISSUE THREAD

**Issue by pintend** [fahadmahmood8/stock-locations-for-woocommerce#157]
This plugin is showing a warning from woocommerce
`This plugin is incompatible with the enabled WooCommerce feature 'High-Performance order storage', it shouldn't be activated. `

https://woocommerce.com/document/high-performance-order-storage/

**Comment by fahadmahmood8** [comment]
Yes, that's correct. It is not compatible with HPOS yet.

**Comment by pintend** [comment]
version 2.7.6 says its compatible with HPOS but I am still getting the error

**Comment by fahadmahmood8** [comment]
What kind of error?

**Comment by pintend** [comment]
It was still showing this message (the message seamed to have come back as i remember it going away after updating)
> This plugin is incompatible with the enabled WooCommerce feature 'High-Performance order storage', it shouldn't be activated. 


UPDATE:
I was having other weird issues with woocommerce so I restarted php which fixed that error and my other issues
I wonder if opcache was causing it

looks like its all good now.

**Comment by fahadmahmood8** [comment]
Strange, so on github I am facing the same response as on wordpress.org support threads. As much as I am responsive, plugins users report me first and check other options later :)

Anyways, thank you for the update.
