### ISSUE TITLE
Site showing product in stock with no stock in warehouse

### ISSUE THREAD

**Issue by LFadden** [fahadmahmood8/stock-locations-for-woocommerce#158]
Hi - in stock locations for warehouse our products are showing as having stock when there is none available. See attached screenshots. We have no stock available of these pants but it is showing 11 in stock to the customer. (the customer is not able to place the order for any but I would like the inventory to show up accurately.) 
thanks
<img width="713" alt="Screenshot 2024-09-06 at 10 39 21 AM" src="https://github.com/user-attachments/assets/d647cad0-052f-4a90-83b5-bdb673fee9c1">
<img width="978" alt="Screenshot 2024-09-06 at 10 39 04 AM" src="https://github.com/user-attachments/assets/3f6548d5-ea19-4218-8f70-aed969ae3dbc">

**Comment by fahadmahmood8** [comment]
Must consider the cron job run so all the inventories can be updated accordingly.
