### ISSUE TITLE
Logs larger then max_allowed_packet - Log toggle

### ISSUE THREAD

**Issue by AntOnKneess** [fahadmahmood8/stock-locations-for-woocommerce#159]
The logging feature in this plugin writes all logs to the same row of the wp_options table, for websites with many products and many quantity updates this leads to a very large row and eventually an error, the full error message is 4gb long:

Got a packet bigger than 'max_allowed_packet' bytes for query UPDATE `wp_options` SET `option_value` = 'a:80449:{i:0;s:188:\"$postId: 87601, $parentPostId: 87601
(product_update_callback / update_additional_fields_for_object / create_item / respond_to_request / dispatch)
 - 02 Jul, 2024 11:55:56 PM\";i:1;s:188:\"$postId: 87606, $parentPostId: 87606
(product_update_callback / update_additional_fields_for_object / create_item / respond_to_request / dispatch)
 - 02 Jul, 2024 11:56:07 PM\";i:2;s:188:\"$postId: 87608, $parentPostId: 87608
(product_update_callback / update_additional_fields_for_object / create_item / respond_to_request / dispatch)
 - 02 Jul, 2024 11:56:34 PM\";i:3;s:188:\"$postId: 87610, $parentPostId: 87610
(product_update_callback / update_additional_fields_for_object / create_item / respond_to_request / dispatch)
 - 02 Jul, 2024 11:56:48 PM\";i:4;s:188:\"$postId: 87612, $parentPostId: 87612
(product_update_callback / update_additional_fields_for_object / create_item / respond_to_request / dispatch)
 - 02 Jul, 2024 11:57:04 PM\";i:5;s:188:\"$postId: 87614,
....
(product_update_callback / update_additional_fields_for_object / update_item / respond_to_request / dispatch) - 09 Aug, 2024 01:52:50 AM\";i:80447;s:190:\"$postId: 110809, $parentPostId: 110809 (product_update_callback / update_additional_fields_for_object / update_item / respond_to_request / dispatch) - 09 Aug, 2024 01:52:59 AM\";i:80448;s:190:\"$postId: 115743, $parentPostId: 115743 (product_update_callback / update_additional_fields_for_object / update_item / respond_to_request / dispatch) - 12 Sep, 2024 12:44:59 AM\";}' WHERE option_name = 'slw_logger' made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_REST_Server->respond_to_request, WC_REST_CRUD_Controller->update_item, WP_REST_Controller->update_additional_fields_for_object, SLW\SRC\Classes\SlwProductRest->product_update_callback, wc_slw_logger, update_option

This is not good for website health and speed, but a lot worse when wp_debug is set to true, as the server attempts to write this out and it potentially crashes one of the services running the website.

A simple solution might be the ability to toggle the log feature on and off.

**Comment by fahadmahmood8** [comment]
I am surprised to the stats you provided because this plugin is not logging anything. I used the following function "wc_slw_logger" to log something if I need to troubleshoot something but all of those function call are already commented. But as you suggested, I have implemented a toggle button and made this function dependent on ON/OFF of this new toggle button under the logs tab. It is a good feature anyways, I am going to mention your name in the changelog for this contribution my friend.
