### ISSUE TITLE
order more products

### ISSUE THREAD

**Issue by BertRoe** [fahadmahmood8/stock-locations-for-woocommerce#160]
Hi 

Is it possible to order more products then the stock value? 
I have stock for my products but when people order more I will make them. The customer doesn't see my stock quantity. My products are always in stock.

Problem:
For products with no location I can only order 1. For ex. a product with stock quantity 5 I cannot choose 3.

Another problem:
When I order a product the stock is not changing.

Hope you can help me.

Bert

**Comment by fahadmahmood8** [comment]
Dear Bert,

Sorry for the late response as I usually respond on wordpress.org support threads. You can certainly order more products than the stock, for that you need to check the box for allow backorder. And product stock will surely update if order gets successful, it is the default feature of WooCommerce.

Thanks,
Fahad
