### ISSUE TITLE
Unsupported operand types: int - string in class-slw-order-item.php:789, helper-slw-stock-allocation.php:374

### ISSUE THREAD

**Issue by pintend** [fahadmahmood8/stock-locations-for-woocommerce#161]
when metadata is missing for a stock location quantity is an empty string instead of 0

`max(0, $remainingQty - '')`
https://github.com/fahadmahmood8/stock-locations-for-woocommerce/blob/4e451430f110e9f9cd2e4ec2c6234d1c581a67dc/src/src/helpers/helper-slw-stock-allocation.php#L374

`$itemQuantity = $itemQuantity - ''`
https://github.com/fahadmahmood8/stock-locations-for-woocommerce/blob/4e451430f110e9f9cd2e4ec2c6234d1c581a67dc/src/src/classes/class-slw-order-item.php#L789

The get_meta calls should cast to int https://github.com/fahadmahmood8/stock-locations-for-woocommerce/blob/4e451430f110e9f9cd2e4ec2c6234d1c581a67dc/src/src/helpers/helper-slw-stock-allocation.php#L183
https://github.com/fahadmahmood8/stock-locations-for-woocommerce/blob/4e451430f110e9f9cd2e4ec2c6234d1c581a67dc/src/src/helpers/helper-slw-stock-allocation.php#L185

`$locations[$idx]->quantity = (int)...`

**Comment by fahadmahmood8** [comment]
You will get this update in the upcoming version, thank you for this contribution, added your name in the changelog too.
