### ISSUE TITLE
Assign customers to locations

### ISSUE THREAD

**Issue by alexmigf** [fahadmahmood8/stock-locations-for-woocommerce#40]
> Also when each customer signs up to the website we need to be able to set them (preferably within the ‘users’ menu) with a designated warehouse location, this is the location where their items will always be shipped from.

https://wordpress.org/support/topic/assign-a-user-to-a-stock-location-2/#post-13582608

**Comment by boelle** [comment]
cant wait for this one,

but then what if the warehouse is sold out and there is one in the next town over

**Comment by takaacstamaas** [comment]
We are waiting for this too.  We have EU & USA warehouse.
So this global setting for default warehouse would be very useful for clients.

By auto detecting, or by seting up manual rules on admin, like:
"EU warehouse" countries: Germany, Austria, United Kingdom, France, etc.
"USA warehouse" countries: California, Florida, Texas, etc.

**Comment by codehouseno** [comment]
Any progress on this one?
Being able to set up manual rules in admin as @takaacstamaas example would be perfect!

**Comment by fahadmahmood8** [comment]
Not yet but I am adding it to the todo list.
